#ifdef __CLING__
#pragma cling optimize(0)
#endif
void DecInvMassCanvas()
{
//=========Macro generated from canvas: DecInvMassCanvas/Decayed particles invariant mass histogram
//=========  (Wed Jan  8 00:00:10 2025) by ROOT version 6.28/06
   TCanvas *DecInvMassCanvas = new TCanvas("DecInvMassCanvas", "Decayed particles invariant mass histogram",0,0,900,600);
   DecInvMassCanvas->SetHighLightColor(2);
   DecInvMassCanvas->Range(-2.5,-2725.275,22.5,24527.48);
   DecInvMassCanvas->SetFillColor(0);
   DecInvMassCanvas->SetBorderMode(0);
   DecInvMassCanvas->SetBorderSize(2);
   DecInvMassCanvas->SetFrameBorderMode(0);
   DecInvMassCanvas->SetFrameBorderMode(0);
   
   TH1F *InvariantsPMasssPofsPdecayedsPparticles__3 = new TH1F("InvariantsPMasssPofsPdecayedsPparticles__3","Invariant Mass of decayed particles distribution",200,0,20);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(7,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(8,451);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(9,11118);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(10,20764);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(11,11105);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(12,7292);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(13,5679);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(14,4602);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(15,3800);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(16,3273);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(17,2968);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(18,2620);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(19,2303);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(20,2119);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(21,1855);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(22,1711);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(23,1535);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(24,1350);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(25,1219);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(26,1152);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(27,1037);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(28,973);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(29,835);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(30,858);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(31,751);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(32,678);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(33,629);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(34,597);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(35,507);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(36,482);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(37,442);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(38,433);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(39,388);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(40,353);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(41,329);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(42,287);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(43,317);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(44,262);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(45,213);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(46,218);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(47,184);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(48,187);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(49,176);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(50,164);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(51,158);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(52,135);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(53,115);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(54,132);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(55,99);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(56,111);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(57,89);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(58,98);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(59,68);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(60,77);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(61,77);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(62,54);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(63,56);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(64,50);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(65,53);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(66,43);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(67,34);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(68,40);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(69,43);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(70,29);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(71,34);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(72,36);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(73,14);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(74,19);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(75,29);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(76,19);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(77,14);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(78,14);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(79,21);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(80,15);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(81,15);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(82,7);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(83,10);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(84,17);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(85,5);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(86,10);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(87,10);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(88,8);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(89,6);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(90,4);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(91,4);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(92,4);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(93,2);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(94,7);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(95,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(96,6);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(97,5);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(98,6);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(99,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(100,3);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(101,3);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(102,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(103,4);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(104,5);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(105,4);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(106,3);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(107,2);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(108,3);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(109,2);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(110,2);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(111,3);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(112,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(121,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(122,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(126,2);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(128,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(131,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(139,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(140,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetBinContent(145,1);
   InvariantsPMasssPofsPdecayedsPparticles__3->SetEntries(100166);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("Invariant Mass of decayed particles");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 100166 ");
   ptstats_LaTex = ptstats->AddText("Mean  =   1.62");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  1.063");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   InvariantsPMasssPofsPdecayedsPparticles__3->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(InvariantsPMasssPofsPdecayedsPparticles__3);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   InvariantsPMasssPofsPdecayedsPparticles__3->SetLineColor(ci);
   InvariantsPMasssPofsPdecayedsPparticles__3->GetXaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdecayedsPparticles__3->GetXaxis()->SetTitleOffset(1);
   InvariantsPMasssPofsPdecayedsPparticles__3->GetXaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdecayedsPparticles__3->GetYaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdecayedsPparticles__3->GetYaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdecayedsPparticles__3->GetZaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdecayedsPparticles__3->GetZaxis()->SetTitleOffset(1);
   InvariantsPMasssPofsPdecayedsPparticles__3->GetZaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdecayedsPparticles__3->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9341608,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Invariant Mass of decayed particles distribution");
   pt->Draw();
   DecInvMassCanvas->Modified();
   DecInvMassCanvas->cd();
   DecInvMassCanvas->SetSelected(DecInvMassCanvas);
}
