#ifdef __CLING__
#pragma cling optimize(0)
#endif
void PkInvMassCanvas()
{
//=========Macro generated from canvas: PkInvMassCanvas/Pion/kaon invariant mass histogram
//=========  (Wed Jan  8 21:58:44 2025) by ROOT version 6.28/06
   TCanvas *PkInvMassCanvas = new TCanvas("PkInvMassCanvas", "Pion/kaon invariant mass histogram",0,0,900,600);
   PkInvMassCanvas->SetHighLightColor(2);
   PkInvMassCanvas->Range(-2.5,-13121.43,22.5,76974.87);
   PkInvMassCanvas->SetFillColor(0);
   PkInvMassCanvas->SetBorderMode(0);
   PkInvMassCanvas->SetBorderSize(2);
   PkInvMassCanvas->SetFrameBorderMode(0);
   PkInvMassCanvas->SetFrameBorderMode(0);
   
   TH1F *InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2 = new TH1F("InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2","Invariant Mass of ... particles with concordant charge sign distribution",200,0,20);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(7,1076);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(8,10921);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(9,64533);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(10,49108);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(11,8335);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(12,3295);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(13,2810);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(14,854);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(15,3479);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(16,2012);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(17,545);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(18,187);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(19,418);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(20,75);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(21,420);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(22,-61);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(23,-9);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(24,-735);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(25,197);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(26,38);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(27,-843);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(28,634);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(29,-554);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(30,161);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(31,-61);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(32,68);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(33,-184);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(34,-180);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(35,-278);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(36,-320);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(37,-156);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(38,-209);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(39,-452);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(40,-91);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(41,46);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(42,204);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(43,-180);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(44,-134);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(45,-53);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(46,-186);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(47,-23);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(48,43);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(49,102);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(50,-112);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(51,32);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(52,17);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(53,-143);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(54,-37);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(55,117);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(56,67);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(57,48);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(58,37);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(59,254);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(60,-31);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(61,15);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(62,-55);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(63,116);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(64,95);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(65,-14);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(66,78);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(67,44);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(68,41);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(69,67);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(70,-30);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(71,-50);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(72,-6);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(73,-69);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(74,-81);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(75,-20);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(76,152);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(77,-7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(78,-86);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(79,-32);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(80,19);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(81,-10);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(82,-15);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(83,-14);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(84,-23);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(85,32);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(86,-10);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(87,15);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(88,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(89,4);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(90,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(91,-16);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(92,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(93,-7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(94,-23);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(95,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(96,7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(97,10);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(98,-6);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(99,-14);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(100,-32);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(101,-10);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(102,9);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(103,7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(104,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(106,-4);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(107,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(108,7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(109,-7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(110,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(111,-8);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(112,14);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(113,-7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(114,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(115,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(116,3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(119,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(120,6);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(121,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(122,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(123,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(124,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(125,4);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(126,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(128,8);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(130,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(131,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(132,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(133,6);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(134,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(135,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(136,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(138,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(139,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(141,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(142,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(143,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(144,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(145,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(146,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(148,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(149,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(150,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(151,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(153,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(155,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(160,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(161,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetEntries(145196);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("Invariant Mass of .... particles with concordant charge sign");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 145196 ");
   ptstats_LaTex = ptstats->AddText("Mean  = 0.8969");
   ptstats_LaTex = ptstats->AddText("Std Dev   =      0");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetLineColor(ci);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetXaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetXaxis()->SetTitleOffset(1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetXaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetYaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetYaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetZaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetZaxis()->SetTitleOffset(1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetZaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9341608,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Invariant Mass of ... particles with concordant charge sign distribution");
   pt->Draw();
   PkInvMassCanvas->Modified();
   PkInvMassCanvas->cd();
   PkInvMassCanvas->SetSelected(PkInvMassCanvas);
}
