#ifdef __CLING__
#pragma cling optimize(0)
#endif
void PkInvMassCanvas()
{
//=========Macro generated from canvas: PkInvMassCanvas/Pion/kaon invariant mass histogram
//=========  (Wed Jan  8 13:11:29 2025) by ROOT version 6.28/06
   TCanvas *PkInvMassCanvas = new TCanvas("PkInvMassCanvas", "Pion/kaon invariant mass histogram",0,0,900,600);
   PkInvMassCanvas->SetHighLightColor(2);
   PkInvMassCanvas->Range(-2.5,-12406.61,22.5,72693.99);
   PkInvMassCanvas->SetFillColor(0);
   PkInvMassCanvas->SetBorderMode(0);
   PkInvMassCanvas->SetBorderSize(2);
   PkInvMassCanvas->SetFrameBorderMode(0);
   PkInvMassCanvas->SetFrameBorderMode(0);
   
   TH1F *InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2 = new TH1F("InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2","Invariant Mass of ... particles with concordant charge sign distribution",200,0,20);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(7,3862);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(8,12100);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(9,60942);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(10,46521);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(11,6957);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(12,5259);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(13,1841);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(14,1037);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(15,2911);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(16,1160);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(17,1326);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(18,1273);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(19,2188);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(20,-14);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(21,1114);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(22,1506);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(23,-67);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(24,454);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(25,-149);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(26,968);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(27,-386);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(28,-252);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(29,-251);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(30,339);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(31,-136);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(32,67);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(33,-809);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(34,374);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(35,-371);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(36,-21);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(37,25);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(38,-191);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(39,-326);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(40,612);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(41,-421);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(42,110);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(43,-108);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(44,-557);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(45,262);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(46,171);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(47,-142);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(48,-161);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(49,153);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(50,-82);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(51,-190);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(52,148);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(53,78);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(54,78);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(55,-13);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(56,29);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(57,-103);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(58,-46);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(59,-52);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(60,-37);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(61,-190);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(62,94);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(63,-63);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(64,-15);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(65,-81);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(66,106);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(67,32);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(68,-65);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(69,77);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(70,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(71,45);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(72,54);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(73,30);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(74,-44);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(75,26);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(76,120);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(77,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(78,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(79,-15);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(80,48);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(81,-18);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(82,-22);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(83,-48);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(84,11);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(85,19);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(86,-15);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(87,3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(88,-14);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(89,28);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(90,17);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(91,-31);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(92,-16);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(93,36);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(94,5);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(95,3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(96,-8);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(97,5);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(98,11);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(99,-9);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(100,-19);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(101,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(102,5);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(103,-11);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(104,-8);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(105,12);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(106,-4);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(107,17);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(108,12);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(109,14);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(110,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(111,3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(112,-8);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(113,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(114,-12);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(116,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(117,9);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(118,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(119,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(120,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(121,3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(122,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(123,-4);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(124,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(126,6);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(127,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(128,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(130,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(131,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(133,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(135,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(136,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(137,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(138,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(141,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(142,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(143,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(144,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(146,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(147,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(148,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(150,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(151,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(152,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(158,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(162,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetEntries(149094);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("Invariant Mass of .... particles with concordant charge sign");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 149094 ");
   ptstats_LaTex = ptstats->AddText("Mean  = 0.9449");
   ptstats_LaTex = ptstats->AddText("Std Dev   = 0.1399");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetLineColor(ci);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetXaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetXaxis()->SetTitleOffset(1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetXaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetYaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetYaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetZaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetZaxis()->SetTitleOffset(1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetZaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9341608,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Invariant Mass of ... particles with concordant charge sign distribution");
   pt->Draw();
   PkInvMassCanvas->Modified();
   PkInvMassCanvas->cd();
   PkInvMassCanvas->SetSelected(PkInvMassCanvas);
}
