#ifdef __CLING__
#pragma cling optimize(0)
#endif
void PkInvMassCanvas()
{
//=========Macro generated from canvas: PkInvMassCanvas/Pion/kaon invariant mass histogram
//=========  (Wed Jan  8 12:37:33 2025) by ROOT version 6.28/06
   TCanvas *PkInvMassCanvas = new TCanvas("PkInvMassCanvas", "Pion/kaon invariant mass histogram",0,0,900,600);
   PkInvMassCanvas->SetHighLightColor(2);
   PkInvMassCanvas->Range(-2.5,-12673.34,22.5,74245.01);
   PkInvMassCanvas->SetFillColor(0);
   PkInvMassCanvas->SetBorderMode(0);
   PkInvMassCanvas->SetBorderSize(2);
   PkInvMassCanvas->SetFrameBorderMode(0);
   PkInvMassCanvas->SetFrameBorderMode(0);
   
   TH1F *InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2 = new TH1F("InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2","Invariant Mass of ... particles with concordant charge sign distribution",200,0,20);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(7,2562);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(8,11579);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(9,62242);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(10,52964);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(11,5691);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(12,3447);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(13,2924);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(14,557);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(15,3939);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(16,300);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(17,965);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(18,1606);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(19,144);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(20,-14);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(21,490);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(22,-454);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(23,-108);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(24,-49);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(25,-828);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(26,-744);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(27,1158);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(28,-27);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(29,1415);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(30,-484);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(31,916);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(32,318);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(33,123);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(34,597);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(35,-117);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(36,-146);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(37,156);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(38,-219);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(39,-158);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(40,-22);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(41,-30);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(42,-159);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(43,236);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(44,-212);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(45,35);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(46,385);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(47,-87);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(48,38);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(49,61);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(50,235);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(51,-337);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(52,-105);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(53,105);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(54,337);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(55,179);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(56,-96);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(57,-241);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(58,6);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(59,58);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(60,-25);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(61,55);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(62,-23);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(63,88);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(64,-110);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(65,80);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(66,-145);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(67,-25);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(68,69);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(69,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(70,17);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(71,-46);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(72,75);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(73,41);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(74,-11);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(75,-80);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(76,15);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(77,-38);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(78,6);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(79,29);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(80,29);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(81,56);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(82,9);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(83,-39);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(84,-5);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(85,-9);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(86,-11);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(87,-44);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(88,5);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(89,8);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(90,34);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(91,15);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(92,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(93,-28);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(94,11);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(95,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(96,-4);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(97,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(98,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(99,-7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(100,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(101,-16);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(102,-8);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(103,-27);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(104,12);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(105,7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(106,7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(108,-5);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(109,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(110,-5);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(111,-11);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(112,-5);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(113,12);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(114,6);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(115,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(116,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(117,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(118,4);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(119,8);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(120,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(121,7);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(122,4);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(123,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(127,5);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(128,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(129,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(130,3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(131,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(132,-3);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(133,5);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(134,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(136,4);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(138,-4);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(139,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(140,2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(141,-2);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(142,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(143,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(144,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(145,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(146,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(147,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(148,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(152,1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(157,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(164,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(171,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetBinContent(178,-1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetEntries(151092);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("Invariant Mass of .... particles with concordant charge sign");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 151092 ");
   ptstats_LaTex = ptstats->AddText("Mean  = 0.9667");
   ptstats_LaTex = ptstats->AddText("Std Dev   = 0.3287");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->SetLineColor(ci);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetXaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetXaxis()->SetTitleOffset(1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetXaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetYaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetYaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetZaxis()->SetLabelFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetZaxis()->SetTitleOffset(1);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->GetZaxis()->SetTitleFont(42);
   InvariantsPMasssPofsPdOdOdOdOsPparticlessPwithsPconcordantsPchargesPsign__2->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9341608,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Invariant Mass of ... particles with concordant charge sign distribution");
   pt->Draw();
   PkInvMassCanvas->Modified();
   PkInvMassCanvas->cd();
   PkInvMassCanvas->SetSelected(PkInvMassCanvas);
}
